from pynput.keyboard import Key
keycodes = dict(
    esc=Key.esc,
    space=Key.space,
    backspace=Key.backspace,
    left=Key.left,
    right=Key.right,
    up=Key.up,
    down=Key.down,
    delete=Key.delete,
    shift=Key.shift,
    alt=Key.alt,
    ctrl=Key.ctrl_l,
    windows=Key.cmd_l,
    tab=Key.tab,
    capslock=Key.caps_lock,
    volup=Key.media_volume_up,
    voldown=Key.media_volume_down,
    mute=Key.media_volume_mute,
    pause=Key.media_play_pause,
    next=Key.media_next,
    prev=Key.media_previous,
    f4=Key.f4,
    enter=Key.enter
)
